spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carrinho_compras?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        ddl-auto: none
        format_sql: true

server:
  port: 8090